# -*- coding: utf-8 -*-
"""trainGPT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tgdPH-aOXRDEJdcaW-kHCZBkEniKxFp4
"""

!pip install openai

#import requests
#from PIL import Image
#from io import BytesIO

import os
import openai

#Assign API key
openai.api_key = "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"

def chatWithGPT(prompt):
  completion = openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
  {"role": "user", "content": prompt}
  ]
  )
  #return print(completion.choices[0].message.content)
  return completion.choices[0].message.content

#below function can used to compare with the final output, BUT note that the outputs you run many times for a same input can have very big difference
def original_metaphor(prompt):
  final_prompt = "Convert this sentence to metaphor sentence: " + prompt
  completion = openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
  {"role": "user", "content": final_prompt}
  ]
  )
  return print(completion.choices[0].message.content)

prompt = 'a dog is flying in the sky'
original_metaphor(prompt)

"""####Reliability Test -- Original output"""

prompt = 'A bird is shooting bullets on a person.'
original_metaphor(prompt)

prompt = 'A bird is shooting bullets on a person.'
original_metaphor(prompt)

prompt = 'A bird is shooting bullets on a person.'
original_metaphor(prompt)

prompt = 'A bird is shooting bullets on a person.'
original_metaphor(prompt)

prompt = 'A bird is shooting bullets on a person.'
original_metaphor(prompt)

"""##Generation of Dataset
###refer to https://images.datacamp.com/image/upload/v1678453027/Marketing/Blog/ChatGPT_Cheat_Sheet.pdf data generation part (start from pg29)

"""

# @title
training_data= [
    {"prompt": "Convert this sentence to a metaphor sentence: A cat rides a bicycle through a rainstorm.->", "completion": """In adversity, one must adapt to survive. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A tree dances gracefully in the moonlight.->", "completion": """Even the silent can express their beauty. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A penguin serves as a DJ at a beach party.->", "completion": """Unusual talents can make anyone shine. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A fish plays chess against a giraffe.->", "completion": """Intelligence is not bound by appearances. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A snail wins the Grand Prix in a race of cheetahs.->", "completion": """Persistence can outshine speed. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A bookshelf serenades a library with love songs.->", "completion": """Knowledge brings joy to the soul. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A cloud practices ballet in the sky.->", "completion": """Grace can be found in unexpected places. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A squirrel composes poetry with acorns.->", "completion": """Creativity knows no boundaries. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A pineapple hosts a talk show for fruit celebrities.->", "completion": """Everyone has a story to share. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A sunflower paints a masterpiece with sunlight.->", "completion": """Art can be the essence of life. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A cat reads Shakespeare to a group of mice.->", "completion": """Wisdom transcends differences. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A giraffe paints a rainbow in a desert.->", "completion": """Creativity can bring life to barren places. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A bear conducts a symphony for a forest audience.->", "completion": """Music can unite even the wildest of hearts. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A turtle wins a marathon against hares.->", "completion": """Slow and steady progress can achieve the impossible. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A crab writes poetry with seashells.->", "completion": """Beauty is where you find it. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A snowflake paints a mural on a blizzard.->", "completion": """Individuality is a work of art. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A snail invents a rocket to reach the moon.->", "completion": """Ambition transcends limitations. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A dolphin writes love letters to the moon.->", "completion": """Love can be a timeless connection. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A treehouse hosts a summit for birds.->", "completion": """Community is found in shared dreams. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A cactus plays the trumpet for a desert crowd.->", "completion": """Music can flourish in unexpected places. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A firefly conducts a light orchestra.->", "completion": """Creativity shines brightest in the dark. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A crocodile hosts a tea party for a group of flamingos.->", "completion": """Hospitality knows no boundaries. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A dragonfly writes poetry with its wings.->", "completion": """Art can take flight in the smallest of moments. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A lion teaches meditation to a group of zebras.->", "completion": """Inner peace is a universal gift. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A kangaroo teaches yoga to a group of frogs.->", "completion": """Balance is a universal lesson. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A sunflower writes poetry with its petals.->", "completion": """Art can bloom from the simplest of forms. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A rocket ship serves as a taxi for aliens.->", "completion": """Innovation knows no borders. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A snowflake hosts a winter fashion show.->", "completion": """Uniqueness is its own style. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A penguin coaches a soccer team of polar bears.->", "completion": """Dedication conquers any field. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A squirrel paints a mural on a skyscraper.->", "completion": """Vision can reach great heights. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A kid blowing with a lemon in his mouth.->", "completion": """A child's laughter carries the sweetness of a lemon breeze. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A man in front of blue light.->", "completion": """An embodiment of tranquility. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: Eggs inside a small nest.->", "completion": """Life's potential, cradled in a cozy embrace. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: Eggs inside a small nest.->", "completion": """Possibilities of existence, nestled in a warm and secure hug.. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: Eggs inside a small nest.->", "completion": """Potential, wrapped gently in the comforting arms of existence.
 \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A small box full of different types of cutler.->", "completion": """Within a compact chest, a symphony of utensils harmonizes, each piece a note in the orchestra of dining. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A small box full of different types of cutler.->", "completion": """In a small box, kitchen tools work together like a team, each one playing its role in making a meal. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A small box full of different types of cutler.->", "completion": """Inside a little chest, kitchen utensils collaborate smoothly, just like musicians in a band, making dining a joyful experience. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A man on display.->", "completion": """A lone figure in the spotlight, the man becomes a canvas for the world's gaze. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A man on display.->", "completion": """A lone figure in the spotlight, The man transforms into a blank canvas, where the world's eyes paint their stories. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A lock with several keys.->", "completion": """A heart with numerous secrets. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A lock with several keys.->", "completion": """A heart, hiding many untold stories. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A lock with several keys.->", "completion": """A heart filled with countless mysteries. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A glass filled with water.->", "completion": """A crystal goblet cradling liquid secrets. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: An ice cream cone covered in ice with the earth melting on top->", "completion": """A frozen treat adorned with frozen layers, the world's troubles slowly dissipate. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: An ice cream cone covered in ice with the earth melting on top->", "completion": """Like an ice cream with layers of serenity, the world's problems melt away bit by bit. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: An ice cream cone covered in ice with the earth melting on top->", "completion": """With each frozen layer, this treat of tranquility gradually melts away the world's worries. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A road with an image of a car.->", "completion": """Path to self-discovery. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A road with an image of a car.->", "completion": """The journey toward understanding oneself. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A road with an image of a car.->", "completion": """The road to discovering your true self. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A person holding up an light bulb.->", "completion": """Path to inspiration. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A person holding up an light bulb.->", "completion": """The winding trail that leads to creative enlightenment. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A person holding up an light bulb.->", "completion": """A meandering path, where each step unveils a new spark of inspiration. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A person flying with balloons in the air..->", "completion": """Dreams taking flight with colorful balloons. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A person flying with balloons in the air..->", "completion": """As dreams ascend like vibrant balloons, they carry us to new heights of possibility. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: The letter O made up of gears and cogwheels.->", "completion": """Precision engineering forming the core of innovation. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: The letter O made up of gears and cogwheels.->", "completion": """Like a finely crafted masterpiece, precision engineering lies at the heart of every innovative breakthrough. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: The letter O made up of gears and cogwheels.->", "completion": """In the world of innovation, precision engineering serves as the solid foundation upon which creativity builds its towering achievements. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A man with a blue shirt holding a globe.->", "completion": """Knowledge in the palm of his hand, a world at his fingertips. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A man with a blue shirt holding a globe.->", "completion": """With knowledge at his fingertips, he holds the entire world within his grasp. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A person on top of the moon, with a telescope in his hands.->", "completion": """Exploration reaching new heights. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A person on top of the moon, with a telescope in his hands.->", "completion": """Exploration soaring to unprecedented altitudes. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A person on top of the moon, with a telescope in his hands.->", "completion": """The pursuit of discovery scaling new peaks. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A woman holding her fingerprint.->", "completion": """A glimpse into her individuality, etched in the lines of her hand. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A woman holding her fingerprint.->", "completion": """Her unique essence is like a story written in the lines of her hand, waiting to be read. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: Two hands holding the earth.->", "completion": """Like protectors of a fragile treasure, we gently hold our world in our hands. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: Two hands holding the earth.->", "completion": """We cradle our world together. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: Two hands holding the earth.->", "completion": """United, we are the guardians cradling the Earth, nurturing its well-being and future. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: Green leaves on the car..->", "completion": """Nature's touch makes the car a peaceful place. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A light bulb surrounded by many barbed.->", "completion": """Like a thorny embrace, innovation is safeguarded from harm and nurtured to grow. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A wooden man holding an axe with a blue clock in the background.->", "completion": """Time ticking away as the wooden figure wields the instrument of change. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A wooden man holding an axe with a blue clock in the background.->", "completion": """Time moves forward as a wooden figure guides the instrument of change. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A wooden man holding an axe with a blue clock in the background.->", "completion": """Like a clock in motion, time progresses while a wooden figure steers the instrument of transformation. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A person dressed up like a dinosaur with a handmade mask on their head.->", "completion": """A prehistoric wanderer in a modern world. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A person dressed up like a dinosaur with a handmade mask on their head.->", "completion": """A traveler from the past navigating a contemporary world. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A person dressed up like a dinosaur with a handmade mask on their head.->", "completion": """Like a relic from ancient times, he roams in our modern era, exploring a new world. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A girl being trained by an Israeli military during her training.->", "completion": """A fragile bud, forced to bloom amidst the thorns of Israeli military training. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A girl being trained by an Israeli military during her training.->", "completion": """Like a delicate bud, compelled to blossom amid the challenges of Israeli military training. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A girl being trained by an Israeli military during her training.->", "completion": """A fragile bud, finding the strength to bloom amidst the thorns of Israeli military training. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: The scale of a heart and brain.->", "completion": """Balance between emotions and intellect tips the scales of life. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: The scale of a heart and brain.->", "completion": """Life's balance hinges on the interplay between emotions and intellect. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: The scale of a heart and brain.->", "completion": """Like a delicate scale, life tilts and turns with the equilibrium of emotions and intellect. \n"""},

 ]

# @title
validation_data= [
    {"prompt": "Convert this sentence to a metaphor sentence: A penguin juggles flamingos at the circus.->", "completion": """Balance in chaos creates wonder. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A koala conducts a symphony of tree leaves.->", "completion": """Harmony lies within diversity. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A butterfly sings opera to a crowd of caterpillars.->", "completion": """Transformation brings new talents. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A teapot explores the cosmos in a rocket ship.->", "completion": """Curiosity knows no bounds. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A pineapple teaches yoga to a group of pineapples.->", "completion": """Inner peace is universal. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A giraffe hosts a cooking show for short animals.->", "completion": """Expertise transcends stature. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A small tree on a rocky area.->", "completion": """Amidst the unforgiving terrain of life, a small tree stands tall, defying the odds. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A small tree on a rocky area.->", "completion": """In life's tough journey, a small tree stands strong, showing us how to overcome challenges. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A small tree on a rocky area.->", "completion": """Like a determined sapling in a rugged world, it reminds us that even small efforts can conquer life's hardships. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A clock hanging off a tree.->", "completion": """Time, like a clock hanging off a tree, remains an ever-present part of nature's grand design. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A clock hanging off a tree.->", "completion": """Time, akin to a clock on a tree, is a constant element in the grand design of nature. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A clock hanging off a tree.->", "completion": """Like a clock on a tree, time is an integral part of the natural order, always ticking forward. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A bottle with an image on it.->", "completion": """A bottle wears a story on its surface. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: Watermelons with sunglasses on top.->", "completion": """"Life's challenges are our 'sunglasses,' with watermelons on top, unexpected moments of joy. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: Watermelons with sunglasses on top.->", "completion": """"Life's challenges are like our protective shades, and every now and then, we discover unexpected moments of joy, like finding a sweet watermelon. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: Watermelons with sunglasses on top.->", "completion": """"Life's difficulties are like sunglasses that occasionally reveal delightful surprises, much like coming across a juicy watermelon on a sunny day. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A sandwich with text on the back.->", "completion": """Like a sandwich layered with hidden stories, life carries the unspoken tales on its back. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A sandwich with text on the back.->", "completion": """Life is like a sandwich with hidden stories between its layers, carrying untold tales along its journey. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A sandwich with text on the back.->", "completion": """Just like a layered sandwich, life holds unspoken stories between its layers, carrying them with grace. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: Wedding cake with a newly bride and groom.->", "completion": """The union of two souls in sweet harmony. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A light bulb surrounded by many barbed.->", "completion": """Innovation protected by a thorny embrace. \n"""},

    {"prompt": "Convert this sentence to a metaphor sentence: A light bulb surrounded by many barbed.->", "completion": """Innovation, sheltered by a protective shield of thorns. \n"""},

 ]

len(training_data),len(validation_data)

import json

training_file_name= "training_data.jsonl"
validation_file_name = "validation_data.jsonl"

def prepare_data(dictionary_data, final_file_name):

	with open(final_file_name, 'w') as outfile:
		for entry in dictionary_data:
			json.dump(entry, outfile)
			outfile.write('\n')

prepare_data(training_data, "training_data.jsonl")
prepare_data(validation_data, "validation_data.jsonl")

#Below code may give some suggestion, decide whether accept or not
!openai tools fine_tunes.prepare_data -f "training_data.jsonl"
!openai tools fine_tunes.prepare_data -f "validation_data.jsonl"

#uploading the training dataset
training_file_create=openai.File.create(
  file=open("training_data_prepared.jsonl", "rb"),
  purpose='fine-tune'
)

#uploading the validation dataset
validation_file_create=openai.File.create(
  file=open("validation_data_prepared.jsonl", "rb"),
  purpose='fine-tune'
)

#Need to copy paste from the above
training_file_id = training_file_create.id
validation_file_id = validation_file_create.id

#configuration
create_args = {
	"training_file": training_file_id,
	"validation_file": validation_file_id,
	"model": "davinci",
	"n_epochs": 15,
	"batch_size": 3,
	"learning_rate_multiplier": 0.3
}

response = openai.FineTune.create(**create_args)
job_id = response["id"]
status = response["status"]

#print(f'Fine-tunning model with jobID: {job_id}.')
#print(f"Training Response: {response}")
#print(f"Training Status: {status}")

#run this so that you know when the fine tuning process is done and can process to next step
import time

status = openai.FineTune.retrieve(id=job_id)["status"]
if status not in ["succeeded", "failed"]:
	print(f'Job not in terminal status: {status}. Waiting.')
	while status not in ["succeeded", "failed"]:
		time.sleep(2)
		status = openai.FineTune.retrieve(id=job_id)["status"]
		print(f'Status: {status}')
else:
	print(f'Finetune job {job_id} finished with status: {status}')

print('Checking other finetune jobs in the subscription.')
result = openai.FineTune.list()
print(f'Found {len(result.data)} finetune jobs.')

#if fine_tuned_model is not Null
#retrieve_response = openai.FineTune.retrieve(id=response.id)
#fine_tuned_model = response.fine_tuned_model
#print(fine_tuned_model)

#if fine_tuned_model is Null
retrieve_response = openai.FineTune.retrieve(response.id)
fine_tuned_model = retrieve_response.fine_tuned_model
fine_tuned_model

#testing
new_prompt = 'A pig wears a crown'
new_prompt = "Convert this sentence to metaphor sentence: " + new_prompt + "->"
answer = openai.Completion.create(
  model=fine_tuned_model,
  prompt=new_prompt
)

print(answer['choices'][0]['text'])

"""###GPT function"""

def gpt(sentence):
  flag = True
  prompt = "Given you the sentence below:\n " + sentence + "\n. Based on the sentence, reply me with exactly 3 lines:\n" + "First line is the sentence after fixing the grammar and structure error of the given sentence. Emphasize again, just the senetence no need add any description or prefix (e.g.'the sentence after fixing:') for the first line output.\nSecond line has only one character: if the scenario described in the sentence make sense in a realistic (NO fictional or imaginative), reply 'Y', or else 'N'.\nThird line is the explanation for the output for second line."
  reply = chatWithGPT(prompt)
  lst = reply.split('\n')
  fixed_senetence = lst[0]
  prompt1 = "Given you the sentence below:\n " + sentence + "\n. Based on the sentence, reply me with exactly 3 lines:\n" + "First line is the sentence after fixing the grammar and structure error of the given sentence. Emphasize again, just the senetence no need add any description or prefix (e.g.'the sentence after fixing:') for the first line output.\nSecond line has only one character: do you think this sentence has a deeper(i.e. have a metaphor meaning) ? If yes, reply 'N', or else 'Y'.\nThird line is the explanation for the output for second line."
  reply1 = chatWithGPT(prompt1)
  lst1 = reply.split('\n')
  if lst[1] == 'N' or 'does not' in lst[2] or '''doesn't''' in lst[2] or 'straightforward' in lst[2] or lst[1] == 'N' or ('does not' not in lst1[2] and '''doesn't''' not in lst1[2]):
    flag = False
  return fixed_senetence, flag

def final(sentence):
  fixed_sentence, make_sense = gpt(sentence)
  if make_sense:
    print (fixed_sentence)
    return
  else:
    new_prompt = "Convert this sentence to metaphor sentence: " + fixed_sentence + "->"
    answer = openai.Completion.create(
      model=fine_tuned_model,
      prompt=new_prompt
    )
    print ("Original sentence: " + fixed_sentence)
    print("BUT I think it has a metaphor meaning: " +answer['choices'][0]['text'])

"""####Grammar Error"""

sentence = "A boy are eating an ice cream"
final(sentence)

"""####Normal Sentence Test"""

sentence = "Some people have a walk in the park"
final(sentence)

sentence = "Two boys are playing badminton."
final(sentence)

"""####Metaphor Sentence Test"""

sentence = "A dog is flying in the sky."
final(sentence)

"""###Reliability Test"""

sentence = "A bird is shooting bullets on a person."
final(sentence)

sentence = "A bird is shooting bullets on a person."
final(sentence)

sentence = "A bird is shooting bullets on a person."
final(sentence)

sentence = "A bird is shooting bullets on a person."
final(sentence)

sentence = "A bird is shooting bullets on a person."
final(sentence)

sentence = "A bird is shooting bullets on a person."
final(sentence)

sentence = "A bird is shooting bullets on a person."
final(sentence)

sentence = "A bird is shooting bullets on a person."
final(sentence)

sentence = "A bird is shooting bullets on a person."
final(sentence)

sentence = "A bird is shooting bullets on a person."
final(sentence)

"""#Another Image captioning model

# BLIP: Inference Demo
 - [Image Captioning](#Image-Captioning)
 - [VQA](#VQA)
 - [Feature Extraction](#Feature-Extraction)
 - [Image Text Matching](#Image-Text-Matching)
"""

# Commented out IPython magic to ensure Python compatibility.
# install requirements
import sys
if 'google.colab' in sys.modules:
    print('Running in Colab.')
    !pip3 install transformers==4.15.0 timm==0.4.12 fairscale==0.4.4
    !git clone https://github.com/salesforce/BLIP
#     %cd BLIP

!pip install timm transformers fairscale

"""# Image Captioning
Perform image captioning using finetuned BLIP model
"""

from PIL import Image
import requests
import torch
from torchvision import transforms
from torchvision.transforms.functional import InterpolationMode

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

def load_demo_image(image_url, image_size, device):
    #img_url = 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/demo.jpg'
    raw_image = Image.open(image_url).convert('RGB')

    w,h = raw_image.size
    display(raw_image.resize((w//5,h//5)))

    transform = transforms.Compose([
        transforms.Resize((image_size,image_size),interpolation=InterpolationMode.BICUBIC),
        transforms.ToTensor(),
        transforms.Normalize((0.48145466, 0.4578275, 0.40821073), (0.26862954, 0.26130258, 0.27577711))
        ])
    image = transform(raw_image).unsqueeze(0).to(device)
    return image

from models.blip import blip_decoder
def original_captioning(image_url):
  image_url = image_url
  image_size = 384
  image = load_demo_image(image_url, image_size=image_size, device=device)

  model_url = 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_capfilt_large.pth'

  model = blip_decoder(pretrained=model_url, image_size=image_size, vit='base')
  model.eval()
  model = model.to(device)

  with torch.no_grad():
      # beam search
      caption = model.generate(image, sample=True, num_beams=3, max_length=20, min_length=5)
      # nucleus sampling
      # caption = model.generate(image, sample=True, top_p=0.9, max_length=20, min_length=5)
      return caption[0]

"""####Cartoon: Dancing cow test"""

image_url = '/content/drive/MyDrive/test report data/dancing_cow.jpg'
c=original_captioning(image_url)
print(c)

"""####Badminton Test"""

image_url = '/content/drive/MyDrive/test report data/badminton.jpg'
c=original_captioning(image_url)
print(c)

"""####Celebrity Test"""

image_url = '/content/drive/MyDrive/test report data/Rock.jpg'
c=original_captioning(image_url)
print(c)

"""####More Celebrity Test"""

image_url = '/content/drive/MyDrive/test report data/taylor_bruno.jpg'
c=original_captioning(image_url)
print(c)

"""####Hidden object test (ghost)"""

image_url = '/content/drive/MyDrive/test report data/ghost.png'
c=original_captioning(image_url)
print(c)

"""####Hidden object test (face)"""

image_url = '/content/drive/MyDrive/test report data/face.jpeg'
c=original_captioning(image_url)
print(c)

"""###Final function: image_captioning"""

def image_captioning(image_url):
  caption = original_captioning(image_url)
  final(caption)

"""###Normal: Football Test"""

image_url = '/content/drive/MyDrive/test report data/football.jpg'
image_captioning(image_url)

"""###Normal:Children Playing Test"""

image_url = '/content/drive/MyDrive/test report data/children.jpeg'
image_captioning(image_url)

"""###Normal:Birthday Test"""

image_url = '/content/drive/MyDrive/test report data/birthday.jpg'
image_captioning(image_url)

"""###Metaphor: Pig with a crown Test"""

image_captioning("/content/drive/MyDrive/test report data/pig.jpg")

"""###Metaphor: Rocket in a brain test"""

image_captioning("/content/drive/MyDrive/test report data/idea.jpg")

"""###Metaphor: Cartoon Hearting Running Test"""

image_captioning("/content/drive/MyDrive/test report data/heart.jpeg")

"""##Go to drive and generate dataset"""

from google.colab import drive
drive.mount('/content/drive',force_remount=True)
import os

from models.blip import blip_decoder
captions = []
for img in os.listdir("/content/drive/MyDrive/dataset_before_b4_getting_caption"):
  image_url = "/content/drive/MyDrive/dataset_before_b4_getting_caption/"+img
  image_size = 384
  image = load_demo_image(image_url, image_size=image_size, device=device)

  model_url = 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_capfilt_large.pth'

  model = blip_decoder(pretrained=model_url, image_size=image_size, vit='base')
  model.eval()
  model = model.to(device)

  with torch.no_grad():
      # beam search
      caption = model.generate(image, sample=True, num_beams=3, max_length=20, min_length=5)
      # nucleus sampling
      # caption = model.generate(image, sample=True, top_p=0.9, max_length=20, min_length=5)
      print('caption: '+caption[0])
      captions.append(caption[0])
with open('caption.txt','w') as fp:
  for caption in captions:
    fp.write(caption+'\n')

import csv

# Define the input and output file names
input_file = 'caption.txt'
output_file = 'caption.csv'

# Open the text file for reading
with open(input_file, 'r') as text_file:
    # Read the lines from the text file
    lines = text_file.readlines()

# Split each line by comma to create a list of values
data = [line.strip('\n') for line in lines]

# print(data)

# Open the CSV file for writing
with open(output_file, 'w', newline='') as csv_file:
    # Create a CSV writer object
    csv_writer = csv.writer(csv_file)

    # Write the data to the CSV file
    csv_writer.writerow(data)

print(f'Conversion from {input_file} to {output_file} completed.')

